services:
  - type: web
    name: dwallet-govbr-local
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATAPREV_BASE_URL
        sync: false
      - key: DATAPREV_API_KEY
        sync: false
      - key: DATAPREV_CLIENT_ID
        sync: false
      - key: DATAPREV_CLIENT_SECRET
        sync: false
      - key: OAUTH_SERVER_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
